// GET ALL BOOK
export const ALL_BOOK_REQUEST = "ALL_BOOK_REQUEST";
export const ALL_BOOK_SUCCESS = "ALL_BOOK_SUCCESS";
export const ALL_BOOK_FAIL = "ALL_BOOK_FAIL";


export const ADMIN_BOOK_REQUEST = "ADMIN_BOOK_REQUEST";
export const ADMIN_BOOK_SUCCESS = "ADMIN_BOOK_SUCCESS";
export const ADMIN_BOOK_FAIL = "ADMIN_BOOK_FAIL";

export const NEW_BOOK_REQUEST = "NEW_BOOK_REQUEST";
export const NEW_BOOK_SUCCESS = "NEW_BOOK_SUCCESS";
export const NEW_BOOK_RESET = "NEW_BOOK_RESET";
export const NEW_BOOK_FAIL = "NEW_BOOK_FAIL";

export const ISSUE_BOOK_REQUEST = "ISSUE_BOOK_REQUEST";
export const ISSUE_BOOK_SUCCESS = "ISSUE_BOOK_SUCCESS";
export const ISSUE_BOOK_RESET = "ISSUE_BOOK_RESET";
export const ISSUE_BOOK_FAIL = "ISSUE_BOOK_FAIL";

export const UPDATE_BOOK_REQUEST = "UPDATE_BOOK_REQUEST";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";
export const UPDATE_BOOK_RESET = "UPDATE_BOOK_RESET";
export const UPDATE_BOOK_FAIL = "UPDATE_BOOK_FAIL";

export const DELETE_BOOK_REQUEST = "DELETE_BOOK_REQUEST";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_RESET = "DELETE_BOOK_RESET";
export const DELETE_BOOK_FAIL = "DELETE_BOOK_FAIL"

export const NEW_REQUEST_BOOK_REQUEST = "NEW_REQUEST_BOOK_REQUEST";
export const NEW_REQUEST_BOOK_SUCCESS = "NEW_REQUEST_BOOK_SUCCESS";
export const NEW_REQUEST_BOOK_FAIL = "NEW_REQUEST_BOOK_FAIL"
export const NEW_REQUEST_BOOK_RESET = "NEW_REQUEST_BOOK_RESET"

export const REQUEST_BOOK_REQUEST = "REQUEST_BOOK_REQUEST";
export const REQUEST_BOOK_SUCCESS = "REQUEST_BOOK_SUCCESS";
export const REQUEST_BOOK_FAIL = "REQUEST_BOOK_FAIL"

// Delete  Requested Books
export const DELETE_REQUESTED_BOOK_REQUEST = "DELETE_REQUESTED_BOOK_REQUEST";
export const DELETE_REQUESTED_BOOK_SUCCESS = "DELETE_REQUESTED_BOOK_SUCCESS";
export const DELETE_REQUESTED_BOOK_FAIL = "DELETE_REQUESTED_BOOK_FAIL";
export const DELETE_REQUESTED_BOOK_RESET = "DELETE_REQUESTED_BOOK_RESET";

// search book for issuing
export const SEARCH_BOOK_REQUEST = "SEARCH_BOOK_REQUEST";
export const SEARCH_BOOK_SUCCESS = "SEARCH_BOOK_SUCCESS";
export const SEARCH_BOOK_FAIL = "SEARCH_BOOK_FAIL";

//get all issued Books
export const ALL_ISSUED_BOOK_REQUEST = "ALL_ISSUED_BOOK_REQUEST";
export const ALL_ISSUED_BOOK_SUCCESS = "ALL_ISSUED_BOOK_SUCCESS";
export const ALL_ISSUED_BOOK_FAIL = "ALL_ISSUED_BOOK_FAIL";

//get  issued Books by user id
export const GET_ISSUED_BOOKS_REQUEST = "GET_ISSUED_BOOKS_REQUEST";
export const GET_ISSUED_BOOKS_SUCCESS = "GET_ISSUED_BOOKS_SUCCESS";
export const GET_ISSUED_BOOKS_FAIL = "GET_ISSUED_BOOKS_FAIL";

// Delete  ISSUED Books
export const DELETE_ISSUED_BOOK_REQUEST = "DELETE_ISSUED_BOOK_REQUEST";
export const DELETE_ISSUED_BOOK_SUCCESS = "DELETE_ISSUED_BOOK_SUCCESS";
export const DELETE_ISSUED_BOOK_FAIL = "DELETE_ISSUED_BOOK_FAIL";
export const DELETE_ISSUED_BOOK_RESET = "DELETE_ISSUED_BOOK_RESET";
// return issue Book

export const RETURN_BOOK_REQUEST = "RETURN_BOOK_REQUEST";
export const RETURN_BOOK_SUCCESS = "RETURN_BOOK_SUCCESS";
export const RETURN_BOOK_FAIL = "RETURN_BOOK_FAIL";

// GET BOOK DETAILS
export const BOOK_DETAILS_REQUEST = "BOOK_DETAILS_REQUEST";
export const BOOK_DETAILS_SUCCESS = "BOOK_DETAILS_SUCCESS";
export const BOOK_DETAILS_FAIL = "BOOK_DEATAILS_FAIL";

export const BOOK_RESERVE_REQUEST = "BOOK_RESERVE_REQUEST";
export const BOOK_RESERVE_SUCCESS = "BOOK_RESERVE_SUCCESS";
export const BOOK_RESERVE_FAIL  = "BOOK_RESERVE_FAIL";
export const BOOK_RESERVE_RESET  = "BOOK_RESERVE_RESET";


export const DELETE_BOOK_RESERVE_REQUEST = "DELETE_BOOK_RESERVE_REQUEST";
export const DELETE_BOOK_RESERVE_SUCCESS = "DELETE_BOOK_RESERVE_SUCCESS";
export const DELETE_BOOK_RESERVE_FAIL  = "DELETE_BOOK_RESERVE_FAIL";
export const DELETE_BOOK_RESERVE_RESET  = "DELETE_BOOK_RESERVE_RESET";

export const ALL_BOOK_RESERVE_REQUEST = "ALL_BOOK_RESERVE_REQUEST";
export const ALL_BOOK_RESERVE_SUCCESS = "ALL_BOOK_RESERVE_SUCCESS";
export const ALL_BOOK_RESERVE_FAIL  = "ALL_BOOK_RESERVE_FAIL";

export const CANCEL_RESERVATION_REQUEST = 'CANCEL_RESERVATION_REQUEST';
export const CANCEL_RESERVATION_SUCCESS = 'CANCEL_RESERVATION_SUCCESS';
export const CANCEL_RESERVATION_FAIL = 'CANCEL_RESERVATION_FAIL';
export const CANCEL_RESERVATION_RESET = 'CANCEL_RESERVATION_RESET';

export const CLEAR_ERRORS = "CLEAR_ERRORS";



